apiVersion: v1
kind: Service
metadata:
  name: java-api-service
spec:
  selector:
    app: java-api
  ports:
  - protocol: TCP
    port: 8081  # External port for API access (adjust if needed)
    targetPort: 8080  # Port exposed by Java API container
  type: ClusterIP  # Makes the service accessible within the cluster
