apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432  # External port for database access (adjust if needed)
    targetPort: 5432  # Port exposed by PostgreSQL container
  type: ClusterIP  
