apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1  # Usually run a single instance of PostgreSQL
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: dkfolefac/postgresword:1  # Use a recommended PostgreSQL image
        ports:
        - containerPort: 5432  # PostgreSQL port
        # ... (Optional environment variables for PostgreSQL configuration)
        # ... (Optional volume mounts for persistent storage)
        env:
          - name: POSTGRES_HOST
            value: postgres  # Service name for the database
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: userw
          - name: POSTGRES_PASSWORD
            value: passwordw
          - name: POSTGRES_NAME
            value: databasew
          
              
